config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'foundry/page', to: "foundry#page"
  resources :listings
  devise_for :users
  root 'home#page'
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  get "/restricted/restricted", to: "restricted#restricted", as: "restricted"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
         
  has_many :listings

  enum role: [:standard, :admin]

  after_initialize do
    if self.new_record?
      self.role ||= :standard
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_paramters, if: :devise_controller?

  
  
  protected 
    def configure_permitted_paramters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end

  private

    # Overwriting the sign_out redirect path method
    def after_sign_out_path_for(resource_or_scope)
      new_user_session_path
    end
end

app/controllers/foundry_controller.rb
class FoundryController < ApplicationController
  def page
    @listings = Listing.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token, only: [:show]
  before_action :authenticate_user! 

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
          name: @listing.name,
          description: @listing.description,
          images: ["https://www.incimages.com/uploaded_files/image/1920x1080/getty_495142964_198701.jpg"],
          amount: (@listing.price * 100).to_i,
          currency: 'aud',
          quantity: 1
        }],
        payment_intent_data: {
          metadata: {
            listing_id: @listing.id,
            user_id: current_user.id
          }
        },
        success_url: "#{root_url}payments/success?eventID=#{@listing.id}",
        cancel_url: "#{root_url}listings"
      )

      @session_id = session.id
      pp session
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    authorize @listing
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end

    @listing = Listing.find(params[:id])
    authorize @listing
    
    if @listing.destroy
      flash[:notice] = "\"#{@listing.name}\" was successfully deleted."
      redirect_to foundry_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :category, :user_id, :avatar)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    # @orders = Order.all
    @orders = Order.where(:user_id => current_user.id )
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:user_id, :listing_id)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    def success 
        listing_id = params[:eventID]
        @listing = Listing.find(listing_id)
        @purchase = Order.find_by_listing_id(listing_id)
    end 

    def webhook 
        payment_id = params[:data][:object][:payment_intent]
        payment = Stripe::PaymentIntent.retrieve(payment_id)
        @listing_id = payment.metadata.listing_id
        @user_id = payment.metadata.user_id
        receipt_url = payment.charges.data[0].receipt_url
        p "Listing id" + @listing_id
        p "user id" + @user_id
        render plain: "Success"

        new_order = Order.create!(:listing_id => @listing_id, :user_id => @user_id, :receipt_url => receipt_url, :payment_intent_id => payment_id)
        p "New Order" + new_order.to_s

        new_payment = Payment.create!(:price => :amount, :user_id => @user_id)
        p "New payment" + new_payment.to_s        
    end

end

app/controllers/restricted_controller.rb
class RestrictedController < ApplicationController
    # before_action :authenticate_user!, only: [:restricted]

    # GET /orders/restricted
    def restricted
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foundry_helper.rb
module FoundryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restricted_helper.rb
module RestrictedHelper
end

app/views/foundry/_card.html.erb
<div class="col-md-4">
    <div class="card text-center card-height shadow p-3 mb-5 rounded gradient-custom" style="width: 18rem;" enable-gradients="true" >
        <%= image_tag listing.avatar, class: "card-img-top" %>
            <div class="card-body">
                <h5 class="card-title"><%= listing.name%></h5>
                <p class="card-text">$<%= listing.price%></p>
                <%= link_to "See More", listing_path(listing.id), method: :get, class: "btn btn-primary btn-center"%>
            </div>
    </div>
</div>

app/views/foundry/page.html.erb
<div class="row">
    <% @listings.each do |listing| %>
        <%= render partial: "card", locals: { listing: listing } %>
    <% end %>
</div>

app/views/home/page.html.erb
<span class="align-middle">
    <div class="jumbotron shadow p-3 mb-5 bg-white rounded position-relative">
    <div class="col">
        <div class="row justify-content-center">
            <h1 class="jumbo-title">Themelio</h1>
        </div>
        <br>
        <div class="row">
            <p class="lead body-text">I am all that I give. What lies ahead is, by nature, beyond my control. I will accept this knowing that I have built a foundation strong enough to bear the weight of any burden, come what may.</p>
        </div>
        <br>
        <div class="row">
            <hr class="my-4">
            <p class="lead col-md-6">
                <%= link_to "Start Building", new_listing_path, method: :get, class: "btn btn-primary btn-lg float-left" %>
            </p>
            <p class="lead col-md-6">
                <%= link_to "The Foundry", foundry_page_path, method: :get, class: "btn btn-primary btn-lg float-right" %>
            </p>
        </div>
    </div>
    </div>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Themelio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="big-body">
    <div class="container">
      <%= render "shared/navbar" %>
      <br>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price, input_html: { min: 0 } %>
    <%= f.input :category, collection: ["Moving", "Thinking", "Eating"] %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: "btn btn-primary btn-center" %> |
<%= link_to 'Back', foundry_page_path, class: "btn btn-primary btn-center" %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.description %></td>
        <td><%= listing.price %></td>
        <td><%= listing.category %></td>
        <td><%= listing.user_id %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @listing.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user.username %>
</p>

<p>
  <%= image_tag @listing.avatar %>
</p>

<button type="button" class="btn btn-primary" data-stripe="payment">Buy<%= number_to_currency(@listing.price) %></button>
<script src="https://js.stripe.com/v3/"></script>
<script>
  document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
    const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
    stripe.redirectToCheckout({
      sessionId: "<%= @session_id %>"
    });
  });
</script>

<%= link_to 'Back', foundry_page_path, class: "btn btn-primary btn-center" %>

<%# limit the user from being able to access the edit button if they were not the creator of the object or an admin %>
<% if policy(@listing).edit? %>
    <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-primary btn-center" %> 
<% end %>

app/views/orders/_card.html.erb
<div class="col-md-4">
    <div class="card text-center card-height" style="width: 18rem;">
        <%= image_tag listing.avatar, class: "card-img-top" %>
            <div class="card-body">
                <h5 class="card-title"><%= listing.name%></h5>
                <p class="card-text">$<%= listing.price%></p>
                <%= link_to "See More", listing_path(listing.id), method: :get, class: "btn btn-primary btn-center"%>
            </div>
    </div>
</div>

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :listing %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Guides</h1>

<table>
  <%# <thead>
    <tr>
      <th>User</th>
      <th>Listing</th>
      <th colspan="3"></th>
    </tr>
  </thead> %>

  <tbody>
    <div class="row">
      <% @orders.each do |order| %>
        <%= render partial: "foundry/card", locals: { listing: order.listing } %>
      <% end %>
    </div> 

    <%# <% @orders.each do |order| %> 
      <%# <tr> %>
        <%# <td><%= order.user_id %></td>
        <%# <td><%= order.listing_id %></td> 
        <%# <td><%= link_to 'Show', order %></td> 
        <%# <td><%= link_to 'Edit', edit_order_path(order) %></td> 
        <%# <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      <%# </tr> %>
    <%# <% end %> 
  </tbody>
</table>

<br>

<%# <%= link_to 'New Order', new_order_path %> 

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<p>
  <strong>Listing:</strong>
  <%= @order.listing_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/payments/success.html.erb
<h1>Payment successful!</h1>

<p>You now have access to <%= @listing.name %> </p> 

<p>Here's your receipt for your records:</p>
<%=link_to "Receipt", @purchase.receipt_url, target: :_blank %>
<br>
<%= link_to "Go to The Foundry", foundry_page_path %>

app/views/restricted/restricted.html.erb
<h1 class="Alexcenter">Alex's Domain</h1>
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6">
            <h1 class="display-4">Alex B:</h1>
            <p class="lead">This page contains super secret information, you should probably sign in if you want to see this, my dude.</p>
            <hr class="my-4">
            <p class="lead">
                <%= link_to "Sign In", new_user_session_path, method: :get, class: "btn btn-primary btn-lg" %>
            </p>
        </div>  
        <div class="col-md-6">
            <%= image_tag "wednesdaymydudeswide", class: "home-image" %>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: background: linear-gradient(to right, rgba(102, 126, 234, 0.5), rgba(118, 75, 162, 0.5));">
  <a class="navbar-brand" href="/">Themelio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex bd-highlight" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "The Foundry", foundry_page_path, class: "nav-link"%>
      </li>
      
      <li class="nav-item dropdown active nav-color">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Stuff
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in?%>
            <%= link_to "My Foundry", orders_path, method: :get, :class => "nav-link" %>
          <% else %>
            <%= link_to "My Foundry", restricted_path, method: :get, :class => "nav-link" %>
          <% end %>
          <%= link_to "FAQ's", foundry_page_path, method: :get, :class => "nav-link" %>
        </div>
      </li>
      <%# will include the merch store in a later iteration %>
      <%# <li class="nav-item active nav-color">
        <a class="nav-link" href="#">Represent <span class="sr-only">(current)</span></a>
      </li> %>
      <li class="nav-item active d-flex bd-highlight float-right nav-color">
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, method: :get, :class => "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>